<?php

namespace App\Tests\Hotel;

use App\Hotel\SearchService;
use PHPUnit\Framework\TestCase;

class SearchServiceTest extends TestCase
{
   /*  public  function  setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub


    }
*/
    public function testSearch()
    {
       $this->assertTrue(true);
    }
}
